services:
  gateway:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: nexstream-express-gateway
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    restart: always
